version: '2'
services:
        nginx:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/lnmp-nginx:latest
                ports:
                        - "443:443"
                        - "80:80"
                volumes:
                        - wp_content:/home/wwwroot/blog.gotocoding.com/wp-content
                networks:
                        - frontend
                depends_on:
                        - php
                        - rssreader
        php:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/lnmp-php:latest
                volumes:
                        - wp_content:/home/wwwroot/blog.gotocoding.com/wp-content
                        - ./wp-config.php:/home/wwwroot/blog.gotocoding.com/wp-config.php
                networks:
                        - frontend
                        - backend
                depends_on:
                        - mysql
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: wp
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_PREFIX: wp_
        rssreader:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/rssreader:latest
                volumes:
                        - ./weixin.conf:/RssReader/server/weixin.conf
                networks:
                        - frontend
                        - backend
                environment:
                        dbaddr: redis
                depends_on:
                        - redis
        mysql:
                image: mariadb:10.3
                networks:
                        - backend
                ports:
                        - "8806:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: wp
                volumes:
                        - mysql_data:/var/lib/mysql
        redis:
                image: redis:4.0
                networks:
                        - backend
                ports:
                        - "63790:6379"
                volumes:
                        - redis_data:/data
networks:
        frontend:
        backend:

volumes:
        mysql_data:
        redis_data:
        wp_content:
