version: '2'
services:
        nginx:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/lnmp-nginx:latest
                ports:
                        - "443:443"
                        - "80:80"
                volumes:
                        - wp_content:/home/wwwroot/blog.gotocoding.com/wp-content
                        - letsencrypt:/etc/letsencrypt
                networks:
                        - frontend
                depends_on:
                        - php
                        - rssreader
                        - cardhelper
                environment:
                        TZ: Asia/Shanghai
        php:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/lnmp-php:latest
                volumes:
                        - wp_content:/home/wwwroot/blog.gotocoding.com/wp-content
                networks:
                        - frontend
                        - backend
                depends_on:
                        - mysql
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: wp
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_PREFIX: wp_
        rssreader:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/rssreader:latest
                networks:
                        - frontend
                        - backend
                environment:
                        dbaddr: redis
                        appid: 'wx738bb0a8533b90b3'
                        secret: '63cf77f077dfcef07b70d82772e23972'
                        template: 'FTJ2mbjR493UUepNbuLboKIyxiMK3qHUWY_wkra3avo'
                        TZ: Asia/Shanghai
                depends_on:
                        - redis
        cardhelper:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/cardhelper:latest
                networks:
                        - frontend
                        - backend
                environment:
                        dbaddr: redis
                        dbindex: 13
                        listen:  '[0::0]:9001'
                        appid: 'wx9b76a8fe5a2faae8'
                        secret: '132f9f7e091609f8f1f5a22cffded0ac'
                        TZ: Asia/Shanghai
                depends_on:
                        - redis
        tunnel:
                image: registry.cn-hangzhou.aliyuncs.com/findstr-vps/tunnel:latest
                ports:
                        - "6002:6002"
                environment:
                        server: '[0::0]:6002'
                        crypt: socket5-tunnel-protect
                        gmailport: 4560
                        TZ: Asia/Shanghai
        mysql:
                image: mariadb:10.3
                networks:
                        - backend
                ports:
                        - "8806:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: wp
                        TZ: Asia/Shanghai
                volumes:
                        - mysql_data:/var/lib/mysql
        redis:
                image: redis:4.0
                networks:
                        - backend
                ports:
                        - "63790:6379"
                environment:
                        TZ: Asia/Shanghai
                volumes:
                        - redis_data:/data
networks:
        frontend:
        backend:

volumes:
        mysql_data:
        redis_data:
        wp_content:
        letsencrypt:
